print("============")
print("BIODATA SAYA")
print("============")
print("Nama: Tedi Mulyadi")
print("Nama Panggilan: Tedi")
print("Nim: 312110114")
print("Tempat Tanggal Lahir: Bogor, 23 januari 2000")
print("Umur: 21 Tahun")
print("Alamat: Kp.Bakan Laje Rt/Rw 001/007 Desa.Babakan Raden Kec.Cariu Kab.Bogor")
print("telepon: 083832846949")
print("============")
print("Assalamualaikum")
print("============")
print("let me introduce my self. my name is Tedi Mulyadi, but you can call me Tedi. My Nim is 312110114. I was born in Bogor and i am 21 years old. I am very glad if you want to invite my house in Kp.Bakan Laje. So don't forget to call me before with the number 083832846949")
print("============")
print("thank you")
